<?php $startTime = microtime(1); ?>
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<style type="text/css" media="screen">
		@import url('/skins/origin-external/reset.css');
		@import url('<?php echo BASE_URL; ?>/skins/local/layouts/<?php echo $this->layout; ?>.css');
		@import url('/skins/origin-external/screen.css');
		@import url('<?php echo BASE_URL; ?>/skins/local/screen.css');
	</style>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/yui/2.8.0r4/build/yahoo/yahoo-min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/yui/2.8.0r4/build/event/event-min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/yui/2.8.0r4/build/json/json-min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/yui/2.8.0r4/build/connection/connection-min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/yui/2.8.0r4/build/datasource/datasource-min.js"></script>

	<script type="text/javascript" src="<?php echo BASE_URL; ?>/js/functions.js"></script>

	<title>Cemeteries</title>
</head>
