<?php
/**
 * @copyright Copyright (C) 2008-2009 City of Bloomington, Indiana. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 */
?>
<div id="aboutCemeteries">
	<h2>About the Cemeteries</h2>
	<ul>
		<li><a href="http://bloomington.in.gov/documents/viewDocument.php?document_id=1745">Rose Hill Cemetery</a></li>
		<li><a href="http://bloomington.in.gov/documents/viewDocument.php?document_id=1747">White Oak Cemetery</a></li>
		<li><a href="http://bloomington.in.gov/documents/viewDocument.php?document_id=1745">Notable Persons</a></li>
		<li><a href="http://bloomington.in.gov/documents/viewDocument.php?document_id=1745">Rose Hill Historic Walking Tour</a></li>
	</ul>
	<h2>Website Support</h2>
	<ul>
		<li><a href="http://bloomington.in.gov/documents/viewDocument.php?document_id=4578">Help</a></li>
		<li><a href="https://bloomington.in.gov/documents/viewDocument.php?document_id=4577">Cemetery Data Download and Service</a></li>
		<li><a href="http://bloomington.in.gov">City of Bloomington</a></li>
	</ul>

</div>
<div id="cemeteryImages">
	<div><img alt="Rose Hill Cemetery" src="<?php echo BASE_URL."/images/rosehill.png"; ?>" /></div>
	<div><img alt="White Oak Cemetery" src="<?php echo BASE_URL."/images/whiteoakweb.jpg"; ?>" /></div>
</div>
